### ISSUE TITLE
[End-to-End Validation] Add Sfc YAML for end-to-end validation

### ISSUE THREAD

**Issue by kevindougherty-noaa** [NOAA-EMC/GDASApp#1088]
sfc.yaml using filters used from [SWELL](https://github.com/GEOS-ESM/swell/blob/develop/src/swell/configuration/jedi/interfaces/geos_atmosphere/observations/sfc.yaml).

specificHumidity, airTemperature, virtualTemperature, windEastward, and windNorthward are all rejceted for types 181, 187, 281 and 287 (https://www.emc.ncep.noaa.gov/mmb/data_processing/prepbufr.doc/table_2.htm)

stationPressure is the only variable that should have filters/error assignments.

### **H(x) Comparison**

JEDI h(x) vs. GSI h(x) for station pressure:

![image](https://github.com/NOAA-EMC/GDASApp/assets/69815622/ec18c926-37e1-4623-bbdc-9da23ac5b36f)

Observations vs. JEDI h(x) for station pressure:

![image](https://github.com/NOAA-EMC/GDASApp/assets/69815622/8248052d-4f93-4dae-a27c-ae00734c0d6e)

JEDI-GSI h(x) difference histogram for station pressure:

![image](https://github.com/NOAA-EMC/GDASApp/assets/69815622/8eb8653c-5712-43c7-8029-a167062cace9)

### **QC Flag Comparison**

![image](https://github.com/NOAA-EMC/GDASApp/assets/69815622/3b03e80e-54f1-430e-947e-096eed455cab)

### **Observation Error**

![image](https://github.com/NOAA-EMC/GDASApp/assets/69815622/7cde93b7-e536-415e-bedd-af70018baa0f)

**Comment by kevindougherty-noaa** [comment]
After testing obs filters to match Emily's `conv_ps.yaml` closer because we are only assimilating `stationPressure`, we ran into some issues where all error values were being NaN'ed using the following filter:

```
# Calculate obs error inflation factors for large discrepancies between model and observations 
- filter: Variable Assignment
  assignments:
  - name: ObsErrorFactorSfcPressure/stationPressure
    type: float
    function:
      name: ObsFunction/ObsErrorFactorSfcPressure
      options:
        geovar_sfc_geomz: surface_geometric_height
        geovar_geomz: geopotential_height
        station_altitude: height 

# Inflate surface pressure observation based on discrepancies between
# model and observations due to terrian
- filter: Perform Action
  filter variables:
  - name: stationPressure
  action:
    name: inflate error
    inflation variable:
      name: ObsErrorFactorSfcPressure/stationPressure
```

After discussion with @ADCollard and @emilyhcliu, we discovered the sfc_geoval .nc4 file was flipped. So we added a condition to the geovals input section of the yaml as such:

```
geovals:
  filename: !ENV sfc_geoval_${CDATE}.nc4
  levels_are_top_down: false
```

This ran appropriately and produced the following output:

![image](https://github.com/NOAA-EMC/GDASApp/assets/69815622/93a478a6-aa74-4524-8aa1-d0b4fe0ed39b)

![image](https://github.com/NOAA-EMC/GDASApp/assets/69815622/d267882e-b6bd-46b8-974b-61e81e9d922e)

These results actually increased the error differences, so we will need to investigate further.
