### ISSUE TITLE
The insitu filters are "broken"

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1165]
The current c384/0.25 test is hanging, removing all the filters for Argo "fixes" the hanging issue, but this is not a solution ...

**Comment by guillaumevernieres** [comment]
Testing:
comment out/remove Kriti's filters and replace by something simple like:
```yaml
      - filter: Perform Action                                                                                                                                                                                                     
        action:                                                                                                                                                                                                                    
          name: assign error                                                                                                                                                                                                       
          error function:                                                                                                                                                                                                          
            name: ObsFunction/LinearCombination                                                                                                                                                                                    
            options:                                                                                                                                                                                                               
              variables:                                                                                                                                                                                                           
              - ObsError/seaSurfaceTemperature                                                                                                                                                                                     
              coefs:                                                                                                                                                                                                               
              - 100.0
 ```
