### ISSUE TITLE
Miscellaneous bugs

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1232]
- [x] **Running out of memory**
The 3DVAR went from using ~0.5TB in June to more than 2-2.5TB as of now (07/30/2024)
 
- [x] **Missing python path to pyioda**
Add/export PYTHONPATH in this script:
```
...../jobs/rocoto/prepoceanobs.sh
```
similarly to what is done for the atm obs.

- [x] **Looks like I was wrong about {{ FIXgfs }}**
I know, shocker!!! 
in the gfsv17 yaml, the  `SOCA_INPUT_FIX_DIR` key needs to be replaced:
```yaml
ocnanal:
  SOCA_INPUT_FIX_DIR: {{ HOMEgfs }}/fix/gdas/soca/1440x1080x75/soca
  SOCA_OBS_LIST: {{ HOMEgfs }}/sorc/gdas.cd/parm/soca/obs/obs_list.yaml
  SOCA_NINNER: 100
```

- [x] **soca MOM_input for the 1/4 deg is outdated**
1 fatal error and a few warnings
We need to remove ```DEFAULT_2018_ANSWERS``` (error) and ```ETA_TOLERANCE_AUX``` (warning)

- [x] **No error trapping in the checkpoint task**
One of the job within that task has been failing but the error was not reported by the script [exgdas_global_marine_analysis_chkpt.sh#L70](https://github.com/NOAA-EMC/GDASApp/blob/5583fbb6884a9b98fb3df76058ea2f51414299a2/scripts/exgdas_global_marine_analysis_chkpt.sh#L70)

- [x] **soca to cice variable change is sometimes failing when using 20+ pe's**
profiling for the 0.25deg res:
![profiling-soca2cice](https://github.com/user-attachments/assets/2d1edcfa-8a69-473d-83ba-d2e4985e578e)
we're currently using 40pe's, which fails most of the time and according to the profiling figure above, it is not optimal.
Switch to 16 after stress testing that layout.  

- [x] **ice background fields are all zeros at 0.25deg res.**
Not quite sure what happened, the low-res seems to be ok.
