### ISSUE TITLE
Profiling of the LETKF with 30 and 80 members and a complete obs space

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1234]
# LETKF Profiling

## Test Configurations

| Test # | Ensemble Size | Nodes | MPI Tasks Per Node | Total MPI Tasks | Total Time (s) | Total Memory (GB) | Description                     |
|--------|---------------|-------|--------------------|-----------------|----------------|-------------------|---------------------------------|
| 1      | 30            | 6     | 5                  | 30              | 0:39:16            | 2487.93 Gb               | Small ensemble, fewer nodes     |
| 2      | 30            | 6     | 10                 | 60              | 0:28:16            | 2250.38 Gb               | Small ensemble, moderate scaling|
| 3      | 30            | 12    | 5                  | 60              | 0:27:30            | 2251.93 Gb               | Small ensemble, more nodes      |
| 4      | 30            | 12    | 10                 | 120             | 0:18:12            | 2842.18 Gb               | Small ensemble, max scaling     |
| 5      | 80            | 6     | 13                 | 78              | OOM            |  OOM               | Large ensemble, fewer nodes     |
| 6      | 80            | 6     | 15                 | 90              | OOM            | OOM               | Large ensemble, moderate scaling|
| 7      | 80            | 12    | 13                 | 156             | OOM            | OOM               | Large ensemble, more nodes      |
| 8      | 80            | 12    | 15                 | 180             | OOM            | OOM               | Large ensemble, max scaling     |
| 9      | 80            | 12    | 20                 | 240             | 0:48:46            | 6411.25 Gb               | Large ensemble, max scaling     |
| 10      | 80            | 12    | 25                 | 300             | 0:49:43            | 6446.97 Gb               | Large ensemble, max scaling     |
| 11      | 80            | 15    | 20                 | 300             | 0:38:50        | 7226.84 Gb              | Large ensemble, max scaling     |
| 12     | 80            | 20    | 20                 | 400             | 0:33:13        | 6951.61 Gb              | Large ensemble, max scaling     |
| 13     | 80            | 25    | 20                 | 500             | 0:28:52        | 7531.27 Gb              | Large ensemble, max scaling     |
| 14     | 80            | 30    | 20                 | 500             | 0:27:12        | 8295.05 Gb              | Large ensemble, max scaling     |
| 15     | 80            | 25    | 25                 | 625             | 0:26:31        | 7968.34 Gb              | Large ensemble, max scaling     |
| 16     | 80            | 25    | 30                 | 750             | 0:24:20       | 8304.30 Gb              | Large ensemble, max scaling     |
| 17     | 80            | 25    | 35                 | 875             | 0:23:51       | 8448.17 Gb              | Large ensemble, max scaling     |
| 18     | 80            | 25    | 40                 | 1000             | 0:22:46      |  8587.88 Gb              | Large ensemble, max scaling     |
| 19     | 80            | 20    | 30                 | 600             | 0:27:40      |  8324.85 Gb              | Large ensemble, max scaling     |
| 20     | 80            | 20    | 40                 | 800             | 0:24:00      |  7573.65 Gb              | Large ensemble, max scaling     |
| 21     | 80            | 20    | 50                 | 1000             | 0:22:53      |  7573.65 Gb              | Large ensemble, max scaling     |
| 22     | 80            | 20    | 60                 | 1200             | OOM      |  OOM              | Large ensemble, max scaling     |
## Notes
- **Nodes**: Fixed as 6 or 12 for all tests.
- **MPI Tasks Per Node**: Adjusted for optimal utilization of each node while keeping within practical limits.
- **Ensemble Size**: Tests performed with 30 and 80 members to evaluate scalability and performance.
- **Total Time (s)**: Measure of total runtime for each configuration (to be recorded post-tests).
- **Total Memory (GB)**: Measure of total memory usage across all nodes (to be recorded post-tests).
- **Description**: Provides a quick overview of the setup and scaling intention for each test case.

**Comment by guillaumevernieres** [comment]
We need to turn off most of the io @AndrewEichmann-NOAA , this is what you currently output:
```yaml
 output:
  datadir: letkf_output/
  date: '2021-03-24T15:00:00Z'
  exp: letkf
  type: ens
output mean prior:
  datadir: letkf_output/
  date: '2021-03-24T15:00:00Z'
  exp: letkf.mean_prior
  type: fc
output variance prior:
  datadir: letkf_output/
  date: '2021-03-24T15:00:00Z'
  exp: letkf.var_prior
  type: fc
output variance posterior:
  datadir: letkf_output/
  date: '2021-03-24T15:00:00Z'
  exp: letkf.var_post
  type: an
output increment:
  datadir: letkf_output/
  date: '2021-03-24T15:00:00Z'
  exp: letkf.inc
  type: ens
```
reduce it to the increments only:
```yaml
 output increment:
  datadir: letkf_output/
  date: '2021-03-24T15:00:00Z'
  exp: letkf.inc
  type: ens
```

**Comment by AndrewEichmann-NOAA** [comment]
Thin in the localization?

**Comment by shlyaeva** [comment]
@AndrewEichmann-NOAA: I think to do that, one could add `max nobs` in the obs localization section (https://github.com/JCSDA-internal/ufo/blob/49ddba60c484bc5b8bac81b660e3b1b0905cd314/src/ufo/obslocalization/ObsHorLocParameters.h#L85), so it'd look something like:
```yaml
obs localizations:
- localization method: Rossby
  ...
  max nobs: 1000 # or whatever makes sense
```
