### ISSUE TITLE
Test the cool skin UFO

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1243]
...

Steps to make it work:
1 - update the field metadata `yaml`
In [.../parm/soca/fields_metadata.yaml](https://github.com/NOAA-EMC/GDASApp/blob/develop/parm/soca/fields_metadata.yaml)
```yaml
- name: sw                                             # name used in soca
  masked: false
  getval name: net_downwelling_shortwave_radiation
  io file: sfc                                            # file type, change to ocean
  io name: sw_rad                                # variable name in the netcdf/mom6 history file 
```

2 - update the variational `yaml`
In [3dvarfgat.yaml#L17](https://github.com/NOAA-EMC/GDASApp/blob/cc4568df41cae28a9222ea7931bfee51466111c9/parm/soca/variational/3dvarfgat.yaml#L17) add the necessary extra variable to run the coolskin ufo (sw, lhf, shf, lw, us)

3 - Update the sst obs config files
for example in [sst_abi_g16_l3c.yaml](https://github.com/NOAA-EMC/GDASApp/blob/develop/parm/soca/obs/config/sst_abi_g16_l3c.yaml) update the obs space to use the cool skin forwad operator. Examples in soca can be found [here](https://github.com/JCSDA-internal/soca/blob/f447233bd7a2f759d49330ffa39a2e4cfb0dfa9e/test/testinput/3dvar.yml#L89)
