### ISSUE TITLE
Clean-up the QC filters

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1514]
Thanks to @emilyhcliu for pointing us to a cleaner implementation.
Re-organize the filters and separate pre-prior and post:
```yaml
      obs pre filters:    
      - # Filters with only obs info
      obs prior filters:  
      - # Filters Before h(x)
      obs post filters:   
      - # Filters post h(x)

        - filter: Domain Check
          where:
          - variable:
              name: GeoVaLs/distance_from_coast
            minvalue: 550e3

       # Example of accepting back obs in a specified box
        - filter: Perform Action
          action:
            name: accept
          where:
          - variable:
              name: MetaData/latitude
            minvalue: 19.71
            maxvalue: 26.7
          - variable:
              name: MetaData/longitude
            minvalue: -99.7
            maxvalue: -79.97
```
