### ISSUE TITLE
Failures in background check when sea_area_fraction is undefined

### ISSUE THREAD

**Issue by shlyaeva** [NOAA-EMC/GDASApp#1739]
Occasionally soca backgroundcheck fails with 
```
Assertion failed: hofx[jobs] != missing in applyFilter, line 177 of /scratch1/NCEPDEV/da/Anna.Shlyaeva/gwtest/sorc/gdas.cd/bundle/ufo/src/ufo/filters/BackgroundCheck.cc
```

Missing values in H(x) often indicate that the obs is outside of the domain or mask (getValues puts missing values where it can't calculate the result of interpolation). 
BackgroundCheck expects that H(x) with missing values are filtered out in the previous QC checks.

This check:
```
      - filter: Domain Check
        where:
        - variable:
            name: GeoVaLs/sea_area_fraction
          minvalue: 0.9
```
filters out observations that are on land according to the model mask in most cases. However, in some cases `GeoVaLs/sea_area_fraction` is a missing value (since it's also geovals, I presume this happens when all the gridpoints used in interpolation are over land).

A simple fix is to expand this check to also QC out obs where `GeoVaLs/sea_area_fraction` is a missing value:
```
      - filter: Domain Check
        where:
        - variable:
            name: GeoVaLs/sea_area_fraction
          value: is_valid
          minvalue: 0.9
```
I've tested this on my failing case, and it solved the issue.
