### ISSUE TITLE
Add "RCPTIM" (receipt time) to the bufr2ioda yaml files

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/GDASApp#254]
The "RCPTIM" (receipt time) is required for operational implementation to check for arrival of new obs and to not perform duplicate QC on the already QC'ed data received previously.

The yamls for the marine obs (profile and surface) need to be updated to include the RCPTIM mnemonic.

**Comment by ShastriPaturi** [comment]
@AndrewEichmann-NOAA do you want to update the yamls and issue a bug fix?
@guillaumevernieres, if the yamls are updated now, it will be helpful with obs latency downstream.

**Comment by AndrewEichmann-NOAA** [comment]
@ShastriPaturi @guillaumevernieres On it

**Comment by AndrewEichmann-NOAA** [comment]
@ShastriPaturi @guillaumevernieres Is there an example of how to handle this? I tried replacing the input time portion with iodaconv/test/testinput/bufr_ncep_adpupa_minu.yaml, which looks like:
```
            datetime:
              year: "[*/YEAR, */RCPTIM/RCYR[1], */RCYR[1]]"
              month: "[*/MNTH, */RCPTIM/RCMO[1], */RCMO[1]]"
              day: "[*/DAYS, */RCPTIM/RCDY[1], */RCDY[1]]"
              hour: "[*/HOUR, */RCPTIM/RCHR[1], */RCHR[1]]"
              minute: "[*/MINU, */RCPTIM/RCMI[1], */RCMI[1]]"
```
but that doesn't change or show how to handle the output.
