### ISSUE TITLE
Add more user defined parameters to the yaml passed to setup_expt

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#269]
## Description
Add more flexibility to the parameters that can be set for an experiment. The new `yaml` would look like this:

```yaml
ocnanal:
  SOCA_INPUT_FIX_DIR: '/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/data/static/72x35x25'
  CASE_ANL: 'C48'
  SOCA_OBS_LIST: ''
  COMIN_OBS: '/scratch2/NCEPDEV/marineda/r2d2'
  SABER_BLOCKS_YAML: ''
  SOCA_NINNER: 50
  R2D2_OBS_SRC: 'gdas_marine'
  R2D2_OBS_DUMP: 's2s_v1'
  NICAS_RESOL: 1
  NICAS_GRID_SIZE: 15000
```
`SABER_BLOCKS_YAML`: will allow us to choose what **B** to use.
`SOCA_OBS_LIST`: point to a user defined obs list
A few nicas parameters used in the initialization of **B**:
 `NICAS_RESOL: 1`
 `NICAS_GRID_SIZE: 15000`
