### ISSUE TITLE
Add (u, v) to the state

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#325]
- Needs to be reflected in the standard dev. files. Compute std dev of rotated and interpolated u, v  
- Add "analysis to model" change of var to `cost function`
```yaml
cost function:
[...]
cost type: 4D-Var
variable change:
    variable change name: Ana2Model
[...]
```
