### ISSUE TITLE
Correlated error for insitu profiles

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#495]
## Deliverable:
- An application that will take as input a `ioda` file containing profile obs of temp and/or salt and output the same file with the addition of a `sequenceNumber` as a unique profile identifier.
- Test and calibrate the vertical decorrelation within 1 cycle
- Document results

### Example for ```InsituTemperature```:

```yaml
    - obs space:
        name: InsituTemperature
        obsdataout:
          engine:
            type: H5File
            obsfile: insitutemp_out.nc
        obsdatain:
          engine:
            type: H5File
            obsfile: insitutemp_in.nc
          obsgrouping:
            group variables: [sequenceNumber]
            sort variable: depth
            sort order: ascending

        simulated variables: [waterTemperature]
      obs operator:
        name: InsituTemperature
      obs error:
         covariance model: within group covariances
         correlation variable name: depth
         correlation lengthscale: 20

      obs filters:
      - *land_mask
      - filter: Background Check
        threshold: 5
```
