### ISSUE TITLE
The Ghrsst2Ioda converter should output C instead of K

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#830]

**Comment by apchoiCMD** [comment]
#### For K
```
Reading: [ghrsst_sst_mb_202107010000.nc4,ghrsst_sst_mb_202107010100.nc4]
seconds since 1981-01-01T00:00:00Z
obsVal:
    Min: 276.708
    Max: 281.714
    Sum: 10051.7
...
```

#### For C
```
Reading: [ghrsst_sst_mb_202107010000.nc4,ghrsst_sst_mb_202107010100.nc4]
seconds since 1981-01-01T00:00:00Z
obsVal:
    Min: 3.558
    Max: 8.5635
    Sum: 218.297
...
```

#### Plot for test of one full GHRSST
![ioda_ghrsst_k_to_c](https://github.com/NOAA-EMC/GDASApp/assets/141867620/9639d8db-6ddd-4365-941d-9f107db219f0)
