### ISSUE TITLE
Overlapping obs windows for insitu and altimeter obs

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#837]
```yaml
- obs space:
    name: adt_rads_all
    dmpdir subdir: ADT
    dmpdir regex: rads_adt_??_???????.nc
    provider: RADS
    output file: adt_rads_all.nc4
    window:
       back: 8         # look back 8 six-hourly obs dumps
       forward: 1    #  look forward 1 six-hourly bin 
```
